# Generated by Django 6.0.3 on 2026-03-15 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('direction', models.CharField(help_text='Entrez le nom de la direction', max_length=200, verbose_name='Direction')),
                ('porteur', models.CharField(max_length=200, verbose_name='Porteur')),
                ('indicateur', models.CharField(max_length=200, verbose_name='Indicateur')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('echeance', models.DateField(verbose_name='Échéance')),
                ('progression', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progression (%)')),
                ('statut', models.CharField(default='en_attente', editable=False, max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Plan d'action",
                'verbose_name_plural': "Plans d'action",
                'ordering': ['-date_creation'],
            },
        ),
    ]
