# Generated by Django 6.0.3 on 2026-03-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaction',
            name='direction',
            field=models.CharField(max_length=200, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='statut',
            field=models.CharField(choices=[('en_attente', '⏳ En attente'), ('en_cours', '🔄 En cours'), ('termine', '✅ Terminé'), ('annule', '❌ Annulé')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
